sudo: required

services:
  - docker

before_install:
  - docker build -t altosecdockertest/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true altosecdockertest/docker-react npm run test -- --coverage
